# Generated by Django 4.2.3 on 2023-07-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'CSV Файл',
                'verbose_name_plural': 'CSV Файлы',
            },
        ),
        migrations.CreateModel(
            name='CSVFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('item', models.CharField(blank=True, default='', max_length=255, verbose_name='Название камня')),
                ('total', models.IntegerField(blank=True, default=0, verbose_name='Общее количество')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Количество')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('csv_file_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.csvfile', verbose_name='CSV Файл парсинга')),
            ],
            options={
                'verbose_name': 'Результат парсинга',
                'verbose_name_plural': 'Результаты парсинга',
                'ordering': ('-data',),
            },
        ),
    ]
